### ISSUE TITLE
Issue with Pytohn 3.6.

### ISSUE THREAD

**Issue by sainisanjay** [breadbread1984/R3DCNN#7]
I tried to run python create_dataset.py with python 3.6, it gives me error as bellow. Seems decoding are different in python 2 and python 3. Any idea how to resolve???
```
Traceback (most recent call last):
  File "create_dataset.py", line 90, in <module>
    video2sample();
  File "create_dataset.py", line 33, in video2sample
    readdata.load_split_nvgesture(file_with_split = file_lists["train"],list_split = train_list)
  File "/home/sanjay/workspace/mytutorial/R3DCNN/readdata.py", line 12, in load_split_nvgesture
    params = line.split(' ')
TypeError: a bytes-like object is required, not 'str'
```

**Comment by breadbread1984** [comment]
readdata.py came with the dataset. the script is for python2. you need to modify it yourself if you prefer to run with python3.

**Comment by sainisanjay** [comment]
When i run with python 2.7 it gave me the error as below:
```
Traceback (most recent call last):
  File "create_dataset.py", line 90, in <module>
    video2sample();
  File "create_dataset.py", line 33, in video2sample
    readdata.load_split_nvgesture(file_with_split = file_lists["train"],list_split = train_list)
  File "/home/sanjay/workspace/mytutorial/R3DCNN/readdata.py", line 17, in load_split_nvgesture
    path = params[0].split(':')[1]
IndexError: list index out of range

```

**Comment by breadbread1984** [comment]
nv's dataset has defects. some labeled frame doesnt exists in the video clip. only rgb channel is correct. so dont try to use other two channels.-------- 原始邮件 --------主题：Re: [breadbread1984/R3DCNN] Issue with Pytohn 3.6. (#7)发件人：Sanjay Saini 收件人：breadbread1984/R3DCNN 抄送：Konquer your Mind ,Comment When i run with python 2.7 it gave me the error as below:
Traceback (most recent call last):
  File "create_dataset.py", line 90, in <module>
    video2sample();
  File "create_dataset.py", line 33, in video2sample
    readdata.load_split_nvgesture(file_with_split = file_lists["train"],list_split = train_list)
  File "/home/sanjay/workspace/mytutorial/R3DCNN/readdata.py", line 17, in load_split_nvgesture
    path = params[0].split(':')[1]
IndexError: list index out of range



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/breadbread1984/R3DCNN","title":"breadbread1984/R3DCNN","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/breadbread1984/R3DCNN"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sainisanjay in #7: When i run with python 2.7 it gave me the error as below:\r\n```\r\nTraceback (most recent call last):\r\n  File \"create_dataset.py\", line 90, in \u003cmodule\u003e\r\n    video2sample();\r\n  File \"create_dataset.py\", line 33, in video2sample\r\n    readdata.load_split_nvgesture(file_with_split = file_lists[\"train\"],list_split = train_list)\r\n  File \"/home/sanjay/workspace/mytutorial/R3DCNN/readdata.py\", line 17, in load_split_nvgesture\r\n    path = params[0].split(':')[1]\r\nIndexError: list index out of range\r\n\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/breadbread1984/R3DCNN/issues/7#issuecomment-449584904"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/breadbread1984/R3DCNN/issues/7#issuecomment-449584904",
"url": "https://github.com/breadbread1984/R3DCNN/issues/7#issuecomment-449584904",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sainisanjay** [comment]
Yes you are right, in order to use only "color" channel, i have to modified only ".lst" file or i have to edit readdata.py file

I have modified the `nvgesture_train_correct.lst` as below:

`/home/sanjay/workspace/mytutorial/Datasets/NVIDIA/Video_data/class_01/subject4_r1 color:sk_color:147:227 label:1 `

however, still i am getting error like:
```

Traceback (most recent call last):
  File "create_dataset.py", line 90, in <module>
    video2sample();
  File "create_dataset.py", line 33, in video2sample
    readdata.load_split_nvgesture(file_with_split = file_lists["train"],list_split = train_list)
  File "/home/sanjay/workspace/mytutorial/R3DCNN/readdata.py", line 17, in load_split_nvgesture
    path = params[0].split(':')[1]
IndexError: list index out of range
```

**Comment by breadbread1984** [comment]
you just keep what readdata.py is to read only color channel. if you want to try other channels, modify the line before the last line of readdata. change sensors[0] to the channel you want.

**Comment by sainisanjay** [comment]
@breadbread1984 i have changed as per your commnet but still i am getting same error.
```
Traceback (most recent call last):
  File "create_dataset.py", line 90, in <module>
    video2sample();
  File "create_dataset.py", line 33, in video2sample
    readdata.load_split_nvgesture(file_with_split = file_lists["train"],list_split = train_list)
  File "/home/sanjay/workspace/mytutorial/R3DCNN/readdata.py", line 17, in load_split_nvgesture
    path = params[0].split(':')[1]
IndexError: list index out of range


```

**Comment by breadbread1984** [comment]
you can step execute the code with pdb to get the name of the video clip causing the problem. and check out whether the video clip is correctly unzipped.

**Comment by sainisanjay** [comment]
Dear @breadbread1984, i am quite new in python thus i am not really sure how to debug python code with pdb?? kindly guide me step by step. Thanks

**Comment by breadbread1984** [comment]
sorry, I can't help you with solving off-topic problem.

**Comment by sainisanjay** [comment]
@breadbread1984 , i have create the dataset for only color channel. After running the `create_dataset.py` i got two files `trainset.tfrecord` and `testset.tfrecord` . However in order to train i need `trained C3D model` can you try to share with me. As i mentioned in another thread i am unable to download from baidu cloud. Please share with me on following drives: GoogleDrive, SharePoint, DropBox,
